import Header from "../../Layout/Header";
import Footer from "../../Layout/Footer";
import Aside from "../../Layout/Aside";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
  <Header />

  <div className="flex flex-1">
    <Aside />
    <main className="flex-1 bg-gray-900 text-white p-6">
      {children}
    </main>
  </div>

  <Footer />
</body>
    </html>
  );
}
